require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - '.git/**/*'
    - 'bin/*'
    - '*.gemspec'
    - 'Gemfile*'
    - 'lib/deadfinder/runner.rb'
    - 'examples/**/*'
    - 'vendor/bundle/**/*'  # Add this line to exclude vendor/bundle directory
  SuggestExtensions: false

Style/MutableConstant:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'lib/deadfinder.rb'
    - 'lib/deadfinder/logger.rb'
    - 'lib/deadfinder/utils.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/deadfinder.rb'
    - 'lib/deadfinder/utils.rb'
    - 'lib/deadfinder/runner.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/deadfinder.rb'
    - 'lib/deadfinder/runner.rb'

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/deadfinder.rb'
    - 'lib/deadfinder/runner.rb'

Lint/SuppressedException:
  Exclude:
    - 'lib/deadfinder.rb'
    - 'lib/deadfinder/runner.rb'

Security/Open:
  Exclude:
    - 'lib/deadfinder.rb'
    - 'lib/deadfinder/runner.rb'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

FactoryBot/CreateList:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExpectOutput:
  Enabled: false

Layout/LineLength:
  Max: 200