name: 'DeadFinder Action'
description: 'Find dead-links (broken links)'
branding:
  icon: 'link'
  color: 'purple'
inputs:
  command:
    description: 'The command to run (file, url, sitemap)'
    required: true
  target:
    description: 'The target for the command'
    required: true
  timeout:
    description: 'Timeout in seconds'
    required: false
    default: ''
  concurrency:
    description: 'Number of concurrency'
    required: false
    default: ''
  silent:
    description: 'Silent mode'
    required: false
    default: 'false'
inputs:
  command:
    description: 'The command to run (file, url, sitemap)'
    required: true
  target:
    description: 'The target for the command'
    required: true
  timeout:
    description: 'Timeout in seconds'
    required: false
    default: ''
  concurrency:
    description: 'Number of concurrency'
    required: false
    default: ''
  silent:
    description: 'Silent mode'
    required: false
    default: 'false'
inputs:
  command:
    description: 'The command to run (file, url, sitemap)'
    required: true
  target:
    description: 'The target for the command'
    required: true
  timeout:
    description: 'Timeout in seconds'
    required: false
    default: ''
  concurrency:
    description: 'Number of concurrency'
    required: false
    default: ''
  silent:
    description: 'Silent mode'
    required: false
    default: 'false'
  headers:
    description: 'Custom HTTP headers to send with request, separated by commas'
    required: false
    default: ''
outputs:
  output: 
    description: 'JSON Result'
runs:
  using: 'docker'
  image: 'github-action/Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.target }}
    - ${{ inputs.timeout }}
    - ${{ inputs.concurrency }}
    - ${{ inputs.silent }}
    - ${{ inputs.headers }}