---
name: Docker Build CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-build-test:
    name: Test Docker Builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - path: "."
            name: "Main Dockerfile"
            context: "."
          - path: "github-action"
            name: "GitHub Action Dockerfile"  
            context: "github-action"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker build - ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.path }}/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=build-test-${{ matrix.path }}
          cache-to: type=gha,mode=max,scope=build-test-${{ matrix.path }}
          tags: |
            deadfinder-test:${{ matrix.path }}
            deadfinder-test:latest

  docker-functionality-test:
    name: Test Docker Functionality
    runs-on: ubuntu-latest
    needs: docker-build-test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build main Docker image for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: deadfinder-test:main
          cache-from: type=gha,scope=build-test-.

      - name: Test Docker image functionality
        run: |
          # Test version command
          docker run --rm deadfinder-test:main deadfinder version
          
          # Test help command
          docker run --rm deadfinder-test:main deadfinder --help
          
          # Test basic URL scanning (will fail due to network restrictions but should not crash)
          docker run --rm deadfinder-test:main deadfinder url https://example.com --timeout=1 --silent || true

      - name: Test GitHub Action Docker image (without publishing base image)
        run: |
          # For the GitHub Action Dockerfile, we need to mock the base image
          # Create a temporary Dockerfile that uses our built image as base
          cat > github-action/Dockerfile.test << 'EOF'
          FROM deadfinder-test:main
          
          # Install jq for JSON processing
          RUN apt-get update && apt-get install -y jq
          
          # Copy the entrypoint script into the container
          COPY entrypoint.sh /entrypoint.sh
          
          # Make the entrypoint script executable
          RUN chmod 755 /entrypoint.sh
          
          # Set the entrypoint to the script
          ENTRYPOINT ["/entrypoint.sh"]
          EOF
          
          # Build the GitHub Action image using our test base
          docker build -t deadfinder-action-test:latest -f github-action/Dockerfile.test github-action/
          
          # Test the GitHub Action entrypoint
          docker run --rm deadfinder-action-test:latest url https://example.com 1 50 true "" "" false false "" "" "" "" "" false "" || true